### ISSUE TITLE
[Request] All new MCBEDOC logos should be removed

### ISSUE THREAD

**Issue by soyeonswife63** [MCBEDOC/mcbedoc.github.io#1]
I designed the logos, and I have commit history & the raw design files as proof. I request all instances of my logo removed.

**Comment by soyeonswife63** [comment]
> > I designed the logos, and I have commit history & the raw design files as proof. I request all instances of my logo removed.
> 
> Removed.

GitHub profile still has it added. Please remove _all_ instances of the logo

**Comment by arsfr** [comment]
> > > I designed the logos, and I have commit history & the raw design files as proof. I request all instances of my logo removed.
> > 
> > 
> > Removed.
> 
> GitHub profile still has it added. Please remove _all_ instances of the logo

okay.

**Comment by arsfr** [comment]
> > > I designed the logos, and I have commit history & the raw design files as proof. I request all instances of my logo removed.
> > 
> > 
> > Removed.
> 
> GitHub profile still has it added. Please remove _all_ instances of the logo

Removed.
